urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('perfil.views',
    url(r'^register/$', 'registro', name='registro'),
    url(r'^forgot-password/$', 'mudar_senha', name='mudar_senha'),
    url(r'^get-token/$', 'get_token', name='get_token'),
)

urlpatterns += patterns('',
    url(r'^login/$', 'perfil.views.entrar', name='login'),
    url(r'^logout/$', 'perfil.views.sair', name='logout'),
)

models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class Perfil(AbstractUser):
    telefone = models.CharField("Phone number", max_length=100, blank=True)
    papel = models.ForeignKey('Papel', null=True, verbose_name="Role", blank=True)
    token = models.CharField(max_length=30, blank=True)
    
    class Meta:
        ordering = ['first_name']

    def __unicode__(self):
        if self.first_name:
            return self.get_full_name()
        else:
            return self.username

    def __str__(self):
        if self.first_name:
            return self.get_full_name()
        else:
            return self.username

class Papel(models.Model): ## User role
    nome = models.CharField("Role name", max_length=300)
    atividades = models.TextField("Assignments")

    def __unicode__(self):
        return self.nome

forms.py
from django import forms
from .models import Perfil

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'telefone')
    password = forms.CharField(widget=forms.PasswordInput, required=True)
    
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(PerfilForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    

views.py
# -*- coding: utf-8 -*-
import string, random
from django.conf import settings
from django.shortcuts import render, get_object_or_404 as g404
from django.http import HttpResponseRedirect as red
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout
from .forms import PerfilForm, LoginForm
from .models import Perfil
 
def registro(request):
    form = PerfilForm()
    if request.POST:
        form = PerfilForm(request.POST)
        if form.is_valid():
            u = form.save(commit=False)
            #u.is_active = False
            u.save()
            return red("/")
    return render(request, "register.html", {'form': form})

def get_token(request):
    uname = request.REQUEST.get('uname', False)
    msg = False
    if uname:
        try:
            token = "".join([random.choice(string.hexdigits) for n in xrange(30)]).upper()
            u = g404(Perfil, username=uname)
            u.token = token
            u.save()
        except:
            msg = "User not found. Contact our support."
            return render(request, "get_token.html", {'msg': msg})
        if u.email:
            uri = settings.BASE_URL + "/perfil/forgot-password/?u="+u.username+"&t="+u.token
            u.email_user("Password change", "To redefine your password, please follow: " + uri)
            msg = "Check your inbox. " + "(" + u.email + ")"
        else:
            msg = "You do not have an e-mail set in your account."
            
    return render(request, "get_token.html", {'msg': msg})

def mudar_senha(request):
    token = request.REQUEST.get('t', False)
    uname = request.REQUEST.get('u', "")
    senha = request.REQUEST.get('s', False)
    msg = False
    if token:
        if uname and senha:
            try:
                u = Perfil.objects.get(username=uname)
                if token == u.token:
                    if senha:
                        u.set_password(senha)
                        u.token = "".join([random.choice(string.hexdigits) for n in xrange(30)]).upper()
                        u.save()
                        uh = authenticate(username=uname, password=senha)
                        login(request, uh)
                        return red('/')
            except Perfil.DoesNotExist:
                msg = "The user does not exist."
        else:
            msg = "Enter the username and the new password."
        
    return render(request, "mudar_senha.html", {'msg': msg, 'token': token, 'uname': uname})

def entrar(request):
    form = LoginForm()
    msg = False
    next = request.REQUEST.get('next', '/')
    e = ""
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            e = form.cleaned_data['username']
            p = form.cleaned_data['password']
            ah = authenticate(username=e, password=p)
            if ah is not None:
                if ah.is_active:
                    login(request, ah)
                    #request.session.set_expiry(7200)
                    return red(next)
                else:
                    msg = "Inactive user"
            else:
                msg = "User or password are wrong."
    return render(request, "login.html", {'msg': msg, 'form': form, 'next': next, 'uname': e})

def sair(request):
    logout(request)
    return red("/")

templates/get_token.html
{% if msg %}
	<div class="alert alert-error">
	<p>{{msg}}</p>
	<a href="/" class="btn btn-primary">back</a>
	</div>
{% endif %}

templates/login.html
{% if msg %}
    <div class="alert alert-error">
    <p>{{msg}}</p>
    <form action="{% url 'perfil:get_token' %}" method="post">
    {% csrf_token %}
        <input name="uname" type="hidden" value="{{uname}}">
        <input type="submit" value="Forgot password">
    </form>
    </div>
{% endif %}

<form method="post" action="{% url 'perfil:login' %}">
{% csrf_token %}
 <div>
 <fieldset>
    	<legend>Sign in</legend>
               <div>
               <label>Login</label>
                {{ form.username }}
               </div>
               <div>
               <label>Password <em>*</em></label>
               {{ form.password }}
               </div>
               <div>
                <input type="submit" value="login" />
                <a href="{% url 'perfil:registro' %}">Register</a>
                <input type="hidden" name="next" value="{{ next }}" />
        </div>
</fieldset>
</div>
    </form>

templates/mudar_senha.html
<!-- JQuery required.  -->
<script>
	$(document).ready(function() {
		$("input[type=submit]").on('click', function(e) {
			if ($("#id_s").val() != $("#id_cs").val()) {
				alert("Passwords do not match.");
				return false;
			}
		});
	});
</script>


{% if msg %}
	<div>
	<p>{{msg}}</p>
	</div>
{% endif %}
<form method="post" action="{% url 'perfil:mudar_senha' %}">
{% csrf_token %}

<fieldset>
	<label for="id_u">Username:</label>
	<input id="id_u" name="u" type="text" value="{{uname}}">
	
	<label for="id_s">New password:</label>
	<input id="id_s" name="s" type="password">
	
	<label for="id_cs">Retype the new password:</label>
	<input id="id_cs" name="cs" type="password">
</fieldset>

<input name="t" type="hidden" value="{{token}}">

<input name="submit" type="submit" value="Send">
</form>

templates/register.html
<!-- Jquery required. -->
<script>
	$(document).ready(function() {
		$("input[type=submit]").on('click', function(e) {
			if ($("#id_password").val() != $("#id_password2").val()) {
				alert("Passwords do not match.");
				return false;
			}
		});
	});
</script>
<form action="{% url 'perfil:registro' %}" method="post">
	{% csrf_token %}
	
	{% if form.non_field_errors %}
		<div>
			{{ form.non_field_errors }}
		</div>
	{% endif %}
	
	<p>Mandatory:</p>
	<div class="form-field">
		<label for="id_username">Username:</label>
		<input id="id_username" maxlength="30" name="username" type="text">
		{% if form.username.errors %}
			<div>
				{{form.username.errors}}
			</div>
		{% endif %}
	</div>
	
	<div class="form-field">
		<label for="id_password">Password:</label>
		<input id="id_password" maxlength="128" name="password" type="password">
		{% if form.password.errors %}
			<div>
				{{form.password.errors}}
			</div>
		{% endif %}
	</div>
	
	<div class="form-field">
		<label for="id_password2">Retype the password:</label>
		<input id="id_password2" maxlength="128" name="password2" type="password">
	</div>
	
	<p>Optional:</p>
	<div class="form-field">
		<label for="id_first_name">First Name:</label>
		<input id="id_first_name" maxlength="30" name="first_name" type="text">
		
	</div>
	
	<div class="form-field">
		<label for="id_last_name">Last Name:</label>
		<input id="id_last_name" maxlength="30" name="last_name" type="text">
		
	</div>
	
	<div class="form-field">
		<label for="id_email">E-mail:</label>
		<input id="id_email" maxlength="75" name="email" type="email">
		{% if form.email.errors %}
			<div>
				{{form.email.errors}}
			</div>
		{% endif %}
	</div>
	
	<div class="form-field">
		<label for="id_telefone">Phone #:</label>
		<input id="id_telefone" maxlength="100" name="telefone" type="text">
		
	</div>
	
	<p><input type="submit" value="Register"></p>
</form>